### ISSUE TITLE
Not getting Jobs

### ISSUE THREAD

**Issue by DonPanino** [solareon/slrn_qbmultijob#1]
![Screenshot 2024-04-03 180819](https://github.com/solareon/slrn_qbmultijob/assets/130209471/2777d695-c1dc-4fe8-9dcc-e98836e59b72)
![Screenshot 2024-04-03 180758](https://github.com/solareon/slrn_qbmultijob/assets/130209471/05a38521-f852-40e4-b8b8-7d211518a574)

Database gets created and saves but the jobs dont appear in the app

**Comment by solareon** [comment]
@DPrpDev can you open up the NUI debugger at [http://localhost:13172/](http://localhost:13172/) and open the app to see if you get a javascript error?

**Comment by DonPanino** [comment]
Only error is 

![Screenshot 2024-04-03 202220](https://github.com/solareon/slrn_qbmultijob/assets/130209471/e2fe686c-2764-4a85-bccb-64657455c940)

**Comment by DonPanino** [comment]
Just gotta change https://slrn_multijob/ to https://slrn_qbmultijob/ in script.js

**Comment by DonPanino** [comment]
i Opened a PR for this @solareon

**Comment by solareon** [comment]
Merged @DPrpDev good catch
